/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CashRegisterScreen: typeof import('./src/views/CashRegisterScreen.vue')['default']
    HomeScreen: typeof import('./src/views/HomeScreen.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalesControlScreen: typeof import('./src/views/SalesControlScreen.vue')['default']
    VerifyAcessScreen: typeof import('./src/views/VerifyAcessScreen.vue')['default']
  }
}
